### ISSUE TITLE
Exceeds 10% of system memory

### ISSUE THREAD

**Issue by hirunifernando** [xuanjihe/speech-emotion-recognition#13]
Hi xuanjihe, 
I got the system memory issue as mentioned below. To train the model I m using 8 GB RAM and 	Processor - i7  . 
Can you give a solution for that? And I would like to know that how much memory needs to do the training process and are they any modifications to optimize the code.
Thank u.

2018-08-31 10:13:53.134003: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:101] Allocation of 5357568000 exceeds 10% of system memory

**Comment by xuanjihe** [comment]
you can reduce the batch size for every timestep, including the evaluation stage.
