### ISSUE TITLE
How to predict an emotion from a new audio file

### ISSUE THREAD

**Issue by hirunifernando** [xuanjihe/speech-emotion-recognition#14]
Hi,
After training a model, I want to predict an emotion of a new audio file by using a trained model. So I want to know what are features do we need to extract from that audio file and how to extract these features. Actually, let me know the process (prediction.py) of predicting emotion from a new audio file.
Thank u very much. Plz reply ASAP.

**Comment by xuanjihe** [comment]
you can save the model and used ExtractMel.py to extract emotional feature, if you want to use this model for service, you can save the model for .pb files.
