### ISSUE TITLE
运行ExtractMel.py出错

### ISSUE THREAD

**Issue by jasonlinuxzhang** [xuanjihe/speech-emotion-recognition#16]
Traceback (most recent call last):
  File "ExtractMel.py", line 389, in <module>
    read_IEMOCAP()
  File "ExtractMel.py", line 200, in read_IEMOCAP
    train_data[train_num,:,:,0] = (part -mean1)/(std1+eps)
ValueError: operands could not be broadcast together with shapes (300,40) (20,) 

请问这是什么原因呢？

**Comment by xuanjihe** [comment]
已经解决，zscore.py里面的filter_num=20,ExtractMel.py里面的filter_num=40
