### ISSUE TITLE
请规范下代码，给点注释。

### ISSUE THREAD

**Issue by xingzai0617** [xuanjihe/speech-emotion-recognition#17]
在ExtractMel.py文件中的cpickle.dump()10个文件，而在model.py中load_data加载数据只返回6个数据，并且那个保存的名字也对不上号，请您详细规范下代码，给点注释谢谢cPickle.dump(Train_data,Train_label,test_data,test_label,valid_data,valid_label,Valid_label,Test_label,pernums_test,pernums_valid)
在model.py中train_data,train_label,test_data,test_label,valid_data,valid_label = cPickle.load(f)

**Comment by xuanjihe** [comment]
已解决
