### ISSUE TITLE
你好，测试后效果达不到论文写的64%，我用了你的model.py两层CNN+LSTM+attention

### ISSUE THREAD

**Issue by xingzai0617** [xuanjihe/speech-emotion-recognition#19]
你好！我有些问题向您请教：
1. model.py 里面的load_data返回的六项数据不对吧；应该返回train_data,train_label, test_data,Test_label, valid_data,Valid_label；
2. 为啥选择1200个train数据（样本平衡考虑）那这样的话样本太少了，在IEMOCAP数据集上应该用4类吧，lables设置为6，去处理4类样本会不会提升模型输出的accuracy；
3. 特征为啥没用FBANK特征+一阶差分+二阶差分，而不去用MFCC特征+一阶差分+二阶差分；
4. 论文用1-6层CNN+LSTM我看效果差别不大，我就用了你的model里面的2层CNN+LSTM+attention结果accuracy才50%；

**Comment by xuanjihe** [comment]
1、返回什么数据你可以根据自己的需要设
2、你可以将高兴的样本重复利用，减少样本不均衡的问题
3、MFCC做了DCT处理，不适合用CNN处理
4、不同的验证集和测试集效果不一致，你可以换另外一个人做验证集和测试集，所以我给出的结果是所有结果的均值和方差
