### ISSUE TITLE
A KeyError

### ISSUE THREAD

**Issue by Haorotu** [xuanjihe/speech-emotion-recognition#24]
您好，请问一下，当我运行ExtracMel.py文件时，出现了一个KeyError，like this：
![image](https://user-images.githubusercontent.com/28502249/49924885-5405b100-fef2-11e8-8cd6-116636a6ccd9.png)
烦请帮忙看一下，是什么问题？感激不尽

**Comment by xuanjihe** [comment]
你可以把wavname打印出来看什么情况

**Comment by Haorotu** [comment]
十分感谢您的回复，冒昧问一下，具体我应该如何打印？我在console输入print(wavname),以及在wavname = filename.split("/")[-1][:-4]后输入print(wavname)，结果均报错，显示wavname没有被定义。

**Comment by xuanjihe** [comment]
我只使用了音频数据，你应该在脚本中打印，脚本执行完后内存会释放内存
