### ISSUE TITLE
Incompatible shapes: [654] vs. [436]

### ISSUE THREAD

**Issue by ramesh720** [xuanjihe/speech-emotion-recognition#28]
while running model.py 
i am getting error 
InvalidArgumentError (see above for traceback): Incompatible shapes: [654] vs. [436]

and my valid data,valid_label looks good
('valid_label==', (436, 4))
('valid_data==', (436, 300, 40, 3))

and the network architecture is 

('layer1 shape', TensorShape([Dimension(None), Dimension(300), Dimension(40), Dimension(256)]))
('layer 2 shape', TensorShape([Dimension(None), Dimension(300), Dimension(10), Dimension(512)]))
(?, 300, 5, 512)
('layer2 shape', TensorShape([Dimension(None), Dimension(300), Dimension(5), Dimension(512)]))
('layer2 shape', TensorShape([Dimension(None), Dimension(200), Dimension(2560)]))
('layer2 shape', TensorShape([Dimension(None), Dimension(2560)]))
('linear1 shape', TensorShape([Dimension(None), Dimension(768)]))
('linear1 shape', TensorShape([Dimension(None), Dimension(768)]))
('linear1 shape', TensorShape([Dimension(None), Dimension(200), Dimension(768)]))
('outputs1 shape', (<tf.Tensor 'LSTM1/fw/fw/transpose:0' shape=(?, 200, 128) dtype=float32>, <tf.Tensor 'ReverseV2:0' shape=(?, 200, 128) dtype=float32>))
('outputs shape', TensorShape([Dimension(None), Dimension(200), Dimension(256)]))
('outputs shape', TensorShape([Dimension(None), Dimension(200), Dimension(256), Dimension(1)]))
('gru shape', TensorShape([Dimension(None), Dimension(256)]))
('fully1 shape', TensorShape([Dimension(None), Dimension(64)]))
('Ylogits shape', TensorShape([Dimension(None), Dimension(4)]))

i checked and i printed all shapes looking like shapes are good . but getting same error. why i am getting more loggits. many of them getting the same error as i get. can you please check sir. Thanking you

**Comment by xuanjihe** [comment]
I have uodate the code and you can try again!
