### ISSUE TITLE
train loss 下降，但valid loss 有下小降，然后大幅上升

### ISSUE THREAD

**Issue by zswzp** [xuanjihe/speech-emotion-recognition#33]
hi，直接用download代码，进行了实验，
1、train loss是稳定下降，但是再valid loss上，前30个迭代是下降，但是后续就开始上升了。应该是过拟合了吧？
2、在论文中提及的64%的UA，我也未复现，请问是进行了什么参数调优吗？
还请指教，谢谢

**Comment by xuanjihe** [comment]
1、按你说的情况应该是过拟合了，你可以加L2和dropout。
2、我不知道你现在的识别率是多少，如果你解决了高兴情感识别率低的问题，识别率还是未达到期望值的话，建议你重新选择session进行训练，再选一个session作为验证和测试，因为训练样本少，不同的训练数据，结果相差比较大。
