### ISSUE TITLE
关于特征提取问题

### ISSUE THREAD

**Issue by XuHunan** [xuanjihe/speech-emotion-recognition#35]
您好，我按照您给出的网址下载下iemocap数据库后，运行程序发现No such file or directory: './IEMOCAP1.pkl'错误，但是在特征提取代码中，output = './IEMOCAP.pkl'这句代码与上下文代码没有联系，导致我无法找出错误。于是我想问：
第一，下载下来的数据库是否在之前就已经处理好了，生成/IEMOCAP.pkl文件
第二，您文中提到openear提取logmel特征，这部分内容代码里面有设计到？？能否用opensmile代替？

**Comment by xuanjihe** [comment]
1、你把IEMOCAP1.pkl改为IEMOCAP.pkl不就可以了，下载的库是语音库，特征需要自己提；
2、我这里是用python提取的，没有用openear，当然可以用opensmile。
