### ISSUE TITLE
关于one_hot编码

### ISSUE THREAD

**Issue by XuHunan** [xuanjihe/speech-emotion-recognition#36]
您好，我目前有几个问题请教:
（1）按照您给出的网址，下载了音频数据，可是在ExtractMel中不出现错误，但是也没有任何结果输出
（2）在one_hot编码时，train_label = dense_to_one_hot(train_label,4)这句出错，会显示IndexError: index 4841 is out of bounds for size 4800，这种出错原因会在哪？
希望能得到您的回复，谢谢！

**Comment by xuanjihe** [comment]
你把train_label打印出来就知道什么情况了

**Comment by XuHunan** [comment]
您好，我将train_data,mean1,std1.....mean3,std3都打印了，全输出0，train_label输出有[-96][111][-92]等，出现的结果就是这样，还是有错误啊？
我是直接下载iemocap语音库后，将文件路径放到程序里面的
望回复，谢谢

**Comment by XuHunan** [comment]
按照您文中 所示只要improvised数据，故是不是要提前删除script数据再插入路径
