### ISSUE TITLE
关于utils.py，关于berlin库

### ISSUE THREAD

**Issue by perfumeWE** [xuanjihe/speech-emotion-recognition#37]
作者您好，我有几个疑问：
（1）在您的程序上，我的utils.py出错，其他都可以运行，我看您给别人回复，model.py可以边训边策，是不是model.py已经包含了utils.py？
（2）你将一个session用作测试集，那验证集？？还是测试集和验证集都在一个session里？
（3）关于beilin库的修改，您能否给一点建议？？

**Comment by xuanjihe** [comment]
1、model.py可以边训练边在验证集上测试，选取模型，如果要在测试集上测试，你还要自己照着验证集的方式进行修改，这不难的；
2、随机选择4个session进行训练，再选择一个session，包含2个人，选择其中一个人进行验证，再选择其中一个人作为测试；
3、对于Berlin库，因为Berlin库数据量较少，很容易过拟合，导致在验证集上效果好，在测试集上效果差，即过拟合验证集，建议对每个说话人选取等量的，随机选取，抽成10份在进行交叉验证吧

**Comment by XuHunan** [comment]
您好，我这几天还是利用你的程序进行改动，添加柏林库后，发现验证的识别率只有40%多，测试更低。依据您的建议，我需要对语音进行划分后，按照比例对每个人选取同样的样本进行交叉验证，刚好十个人，能不能采取十折交叉验证？？此外，选取等量的样本，这样做会不造成剩下的样本并未进行试验

**Comment by perfumeWE** [comment]
您好，我这几天先用您的程序试了beilin库，发现验证集的识别率只有40%多，测试集更低。依据您的建议：
（1）将语音进行划分等长语句之后，按照一定的比例进行抽取，刚好十个人，能否直接利用十折交叉验证？这样，抽取后，剩下的语音片段不参与实验？？
（2）目前我在model.py里面验证集的识别率达到了72%，将保留好的模型运用到utils中，发现验证集的识别率却降低好多，这是为什么？？最好的模型下的验证识别率不应该就是72%不变吗？？
期待回复，谢谢
