### ISSUE TITLE
模型过拟合问题，如何选取参数

### ISSUE THREAD

**Issue by rphao1995** [xuanjihe/speech-emotion-recognition#5]
你好。
我运行的模型在训练集在300 steps左右时acc = 90%，然而验证集Best UA只有39%，测试集UA也只有31%，请问这是参数选取的问题吗？我该如何选取参数？

![image](https://user-images.githubusercontent.com/25152164/43123341-764c8362-8f56-11e8-8750-8990f1bd4f22.png)
![image](https://user-images.githubusercontent.com/25152164/43123005-7c8cc580-8f55-11e8-8b94-674356793aaa.png)
![image](https://user-images.githubusercontent.com/25152164/43123025-89daca66-8f55-11e8-81a9-7c0b84163b4d.png)

我把 zscore.py 中的 `filter_num=20` 改成 `filter_num=40`，crnn.py中判断是否启用attention机制的`if self.attention is not None:` 改成 `if self.attention:`，然后按如下顺序运行代码
```
python zscore.py
python ExtractMel.py
python train.py --attention True
python utils.py --attention True
```

最后，这代码是文章AUTOMATIC SPEECH EMOTION RECOGNITION USING RECURRENT NEURAL NETWORKS WITH LOCAL ATTENTION的实现吗？我应该怎样复现文章的结果

**Comment by xuanjihe** [comment]
这个代码不是复现那篇论文的，我的论文已经上传到github了，你可以去看看，另外有好几个地方是需要进行优化的，包括学习率调小一点，然后优化不用那么麻烦，直接用adam优化器，attention.py要简化成local attention里面的一样，差不多就能复现了

**Comment by xuanjihe** [comment]
另外，你还要解决训练类别不均衡的问题

**Comment by zh794390558** [comment]
这个代码能复现你的论文结果吗？

**Comment by xuanjihe** [comment]
@zh794390558 你只要解决了训练类别不均衡问题，是可以复现的，每组实验跑5次，避免随机参数初始化的偶然性
